### ISSUE TITLE
Использование переменных окружения

### ISSUE THREAD

**Issue by Findoss** [Findoss/Hunt-map#59]
Для удобства при разработке

- [ ] https://create-react-app.dev/docs/adding-custom-environment-variables/
- [ ] добавить в глобальные константы `IS_DEV` и `IS_PROD`

**Comment by Findoss** [comment]
https://habr.com/ru/company/ruvds/blog/351254/

**Comment by PavelEgorov-ru** [comment]
Я пока не до конца понимаю, как конкретно мы будем использовать переменные окружения. 

Вижу пока такой вариант:
В переменных IS_DEV и IS_PROD мы получаем болевое значение `const IS_DEV = process.env.NODE_ENV === 'development'` и `const IS_PROD = process.env.NODE_ENV === 'production'`. Далее мы определяем initialState для mapSlice в зависимости от того, какая из них true. Для разработки у нас в initialState будет добавляться тестовая нарезанная карта.

**Comment by PavelEgorov-ru** [comment]
Либо второй вариант. Вынести сами объекты начального варианта стейта в эти константы, а при при сборке в mapSlice определять, какая из них будет в initialState в зависимости от значения process.env.NODE_ENV

**Comment by Findoss** [comment]
@PavelEgorov-ru отписался в тг
