### ISSUE TITLE
How come this shut down?

### ISSUE THREAD

**Issue by Wolfhound905** [Findoss/Hunt-map#81]
I think I would be willing to host if this is going to stay down forever.

**Comment by Findoss** [comment]
@Wolfhound905 hi, You can use any of my sources. The best state of the project (but not production) in the branch dev. Perhaps I will answer questions about the code

If we are talking about the domain, we can discuss personally, I do not mind translating it.

**Comment by Findoss** [comment]
> How come this shut down?


I have no strength to support the project

**Comment by Wolfhound905** [comment]
> If we are talking about the domain, we can discuss personally, I do not mind translating it.

Feel free to hit me up on Discord. Wolfhound905#1234

There I can tell you what plans I have with the project

**Comment by Helmbearer** [comment]
I am interested to work on the map as well. Was thinking about making my own one from scratch, but since you stopped developing it I am interested in developing it further.

**Comment by donum** [comment]
I'm already working on a replacement (https://hunt.rip) and made quite some progress, having another update in the pipeline. Would also love to take over the domain, eXtr3m0#4090 on discord.

**Comment by Helmbearer** [comment]
@Findoss I just had a talk with @donum and @Wolfhound905 about how we could might colaborate. Can I contact you somehow to talk about the domain?

**Comment by Findoss** [comment]
@Helmbearer discord Findoss#4833
